apiVersion: v1
kind: Service
metadata:
  name: karga-app-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: karga-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080