apiVersion: v1
kind: Secret
metadata:
  name: karga-secret
  namespace: dev
type: Opaque
data:
  # === MySQL (Operator) ===
  SPRING_DATASOURCE_PASSWORD: "..." # eg: echo -n 'root-password' | base64

  # === JWT (Application) ===
  APP_JWT_SECRET: "..." # eg: echo -n 'jwt-secret-key' | base64

  # === Kafka (Bitnami) ===

  SPRING_KAFKA_USERNAME: "dXNlcjE=" # base64 for 'user1' eg: echo -n 'user1' | base64
  SPRING_KAFKA_PASSWORD: "..." # eg: kubectl get secret karga-kafka-user-passwords -n dev -o jsonpath='{.data.client-passwords}'
  SPRING_KAFKA_TRUSTSTORE_PASSWORD: "" # eg: echo -n 'kafka-truststore-password' | base64

  # === Redis (Bitnami) ===
  SPRING_DATA_REDIS_PASSWORD: "" # eg: kubectl get secret karga-redis -n dev -o jsonpath='{.data.redis-password}'

  STRIPE_APIKEY: "..." # eg: echo -n 'your_stripe_api_key' | base64