apiVersion: apps/v1
kind: Deployment
metadata:
  name: karga-app-deployment
  namespace: dev
  labels:
    app: karga-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karga-app
  template:
    metadata:
      labels:
        app: karga-app
    spec:
      containers:
        - name: karga-app
          image: localhost/karga-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: karga-config
            - secretRef:
                name: karga-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20